import { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { FileText, ArrowRight, Plus, Loader2 } from 'lucide-react';
import { PageHeader } from '@/components/common/PageHeader';
import { Card } from '@/components/common/Card';
import { LoadingState, EmptyState } from '@/components/common/States';
import { RiskBadge } from '@/components/common/Badges';
import { formatDate } from '@/utils/format';
import { reportService } from '@/services/reportService';
import { caseService } from '@/services/caseService';
import { evidenceService } from '@/services/evidenceService';
import { auditService } from '@/services/auditService';
import { demoTimeline } from '@/data/demoTimeline';
import { useToast } from '@/hooks/useToast';
import { useAuth } from '@/hooks/useAuth';
import type { InvestigationCase } from '@/types/case';

interface ReportMeta {
  reportId: string;
  caseId: string;
  caseTitle: string;
  generatedBy: string;
  generatedAt: string;
  riskLevel: string;
  evidenceCount: number;
}

export default function Reports() {
  const navigate = useNavigate();
  const { toast } = useToast();
  const { user } = useAuth();
  const [reports, setReports] = useState<ReportMeta[]>([]);
  const [cases, setCases] = useState<InvestigationCase[]>([]);
  const [loading, setLoading] = useState(true);
  const [generatingCaseId, setGeneratingCaseId] = useState<string | null>(null);

  useEffect(() => {
    Promise.all([reportService.listReports(), caseService.getCases()]).then(([r, c]) => {
      setReports(r);
      setCases(c);
      setLoading(false);
    });
  }, []);

  const handleGenerate = async (caseId: string) => {
    const caseData = cases.find((c) => c.caseId === caseId);
    if (!caseData) return;
    setGeneratingCaseId(caseId);
    const evidence = await evidenceService.getByCaseId(caseId);
    const timeline = demoTimeline.filter((t) => evidence.some((e) => e.filename === t.evidence));
    const logs = await auditService.getLogs();
    const report = await reportService.generateReport(
      caseData,
      evidence,
      timeline,
      logs,
      [],
      user?.name ?? 'Investigator'
    );
    auditService.log(user?.email ?? 'unknown', 'Report Generated', report.reportId, `Forensic report for ${caseId}`);
    setGeneratingCaseId(null);
    toast('success', `Report ${report.reportId} generated.`);
    navigate(`/reports/${report.reportId}`);
  };

  return (
    <div className="space-y-6">
      <PageHeader title="Reports" subtitle="Generate and view forensic investigation reports." />

      {/* Generate from existing cases */}
      <Card className="p-5">
        <h3 className="text-sm font-medium text-slate-300 mb-3">Generate New Report</h3>
        <div className="flex flex-wrap gap-2">
          {cases.map((c) => (
            <button
              key={c.caseId}
              onClick={() => handleGenerate(c.caseId)}
              disabled={generatingCaseId === c.caseId}
              className="inline-flex items-center gap-2 rounded-lg border border-slate-700 px-3 py-2 text-sm text-slate-200 hover:bg-slate-800 disabled:opacity-50"
            >
              {generatingCaseId === c.caseId ? (
                <Loader2 className="h-3.5 w-3.5 animate-spin" />
              ) : (
                <Plus className="h-3.5 w-3.5" />
              )}
              {c.caseId} — {c.title.length > 24 ? c.title.slice(0, 24) + '...' : c.title}
            </button>
          ))}
        </div>
      </Card>

      {loading ? (
        <LoadingState label="Loading reports..." />
      ) : reports.length === 0 ? (
        <Card>
          <EmptyState
            icon={FileText}
            title="No reports yet"
            description="Generate a forensic report from any case above."
          />
        </Card>
      ) : (
        <Card className="overflow-hidden">
          <div className="overflow-x-auto scrollbar-thin">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-slate-800 text-left text-xs text-slate-500">
                  <th className="px-5 py-3 font-medium">Report ID</th>
                  <th className="px-5 py-3 font-medium">Case</th>
                  <th className="px-5 py-3 font-medium">Generated By</th>
                  <th className="px-5 py-3 font-medium">Date</th>
                  <th className="px-5 py-3 font-medium">Risk Level</th>
                  <th className="px-5 py-3 font-medium">Evidence Count</th>
                  <th className="px-5 py-3 font-medium"></th>
                </tr>
              </thead>
              <tbody>
                {reports.map((r) => (
                  <tr key={r.reportId} className="border-b border-slate-800/50 hover:bg-slate-800/30">
                    <td className="px-5 py-3 font-mono text-xs text-cyan-400">{r.reportId}</td>
                    <td className="px-5 py-3 text-slate-200 truncate max-w-[180px]">{r.caseTitle}</td>
                    <td className="px-5 py-3 text-slate-400 text-xs">{r.generatedBy}</td>
                    <td className="px-5 py-3 text-slate-400 text-xs">{formatDate(r.generatedAt)}</td>
                    <td className="px-5 py-3"><RiskBadge level={r.riskLevel as 'LOW' | 'MEDIUM' | 'HIGH'} /></td>
                    <td className="px-5 py-3 text-slate-300">{r.evidenceCount}</td>
                    <td className="px-5 py-3">
                      <Link
                        to={`/reports/${r.reportId}`}
                        className="inline-flex items-center gap-1 text-cyan-400 hover:text-cyan-300 text-xs"
                      >
                        View Report <ArrowRight className="h-3 w-3" />
                      </Link>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </Card>
      )}
    </div>
  );
}
