import { useEffect, useState } from 'react';
import { useParams, Link, useNavigate } from 'react-router-dom';
import { ArrowLeft, Printer, ShieldCheck, Loader2 } from 'lucide-react';
import { Card } from '@/components/common/Card';
import { RiskBadge, IntegrityBadge } from '@/components/common/Badges';
import { LoadingState, EmptyState } from '@/components/common/States';
import { reportService } from '@/services/reportService';
import { formatDate, formatDateTime } from '@/utils/format';
import type { ForensicReport } from '@/services/reportService';

export default function ReportDetails() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const [report, setReport] = useState<ForensicReport | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!id) return;
    reportService.getReport(id).then((r) => {
      setReport(r);
      setLoading(false);
    });
  }, [id]);

  const handlePrint = () => {
    window.print();
  };

  if (loading) return <LoadingState label="Loading report..." />;
  if (!report) {
    return (
      <Card>
        <EmptyState
          title="Report not found"
          description="The report you are looking for does not exist."
          action={<Link to="/reports" className="text-cyan-400 hover:text-cyan-300">Back to Reports</Link>}
        />
      </Card>
    );
  }

  const { case: caseData, evidence, timeline, auditLogs, notes, riskDistribution } = report;

  const sectionTitle = 'text-sm font-semibold text-slate-100 border-b border-slate-800 pb-2 mb-3 print-section';

  return (
    <div className="space-y-6">
      {/* Toolbar (hidden in print) */}
      <div className="flex items-center justify-between no-print">
        <Link to="/reports" className="inline-flex items-center gap-2 text-sm text-slate-400 hover:text-slate-200">
          <ArrowLeft className="h-4 w-4" />
          Back to Reports
        </Link>
        <button
          onClick={handlePrint}
          className="inline-flex items-center gap-2 rounded-lg bg-cyan-500/90 px-4 py-2 text-sm font-medium text-white hover:bg-cyan-500"
        >
          <Printer className="h-4 w-4" />
          Print Report
        </button>
      </div>

      {/* Report document */}
      <Card className="p-8 print-page">
        {/* Header */}
        <div className="flex items-center gap-3 border-b-2 border-slate-700 pb-4 mb-6">
          <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-cyan-500/10 border border-cyan-500/30">
            <ShieldCheck className="h-5 w-5 text-cyan-400" />
          </div>
          <div>
            <p className="text-lg font-bold text-slate-100">CYBERTRACE AI</p>
            <p className="text-xs text-slate-400">Digital Forensic Investigation Report</p>
          </div>
          <div className="ml-auto text-right">
            <p className="text-xs text-slate-500">Report ID</p>
            <p className="font-mono text-sm text-cyan-400">{report.reportId}</p>
          </div>
        </div>

        {/* 1. Case Information */}
        <section className="mb-6 print-section">
          <h2 className={sectionTitle}>1. Case Information</h2>
          <div className="grid grid-cols-2 gap-3 text-sm">
            <div><span className="text-slate-500">Case ID:</span> <span className="text-slate-200 font-mono">{caseData.caseId}</span></div>
            <div><span className="text-slate-500">Status:</span> <span className="text-slate-200">{caseData.status}</span></div>
            <div><span className="text-slate-500">Title:</span> <span className="text-slate-200">{caseData.title}</span></div>
            <div><span className="text-slate-500">Priority:</span> <span className="text-slate-200">{caseData.priority}</span></div>
            <div><span className="text-slate-500">Investigator:</span> <span className="text-slate-200">{caseData.investigator}</span></div>
            <div><span className="text-slate-500">Created:</span> <span className="text-slate-200">{formatDate(caseData.createdAt)}</span></div>
            <div><span className="text-slate-500">Updated:</span> <span className="text-slate-200">{formatDate(caseData.updatedAt)}</span></div>
            <div><span className="text-slate-500">Generated By:</span> <span className="text-slate-200">{report.generatedBy}</span></div>
          </div>
          <p className="mt-3 text-sm text-slate-300">{caseData.description}</p>
        </section>

        {/* 2. Investigation Summary */}
        <section className="mb-6 print-section">
          <h2 className={sectionTitle}>2. Investigation Summary</h2>
          <p className="text-sm text-slate-300">
            This report documents the forensic investigation of case {caseData.caseId}. A total of {evidence.length} evidence
            artifacts were collected and analyzed using automated triage. {riskDistribution.high} artifact(s) were classified
            as high-risk and require prioritized manual review.
          </p>
        </section>

        {/* 3. Evidence Summary */}
        <section className="mb-6 print-section">
          <h2 className={sectionTitle}>3. Evidence Summary</h2>
          <table className="w-full text-xs">
            <thead>
              <tr className="border-b border-slate-800 text-left text-slate-500">
                <th className="py-2 pr-3">Evidence ID</th>
                <th className="py-2 pr-3">Filename</th>
                <th className="py-2 pr-3">Type</th>
                <th className="py-2 pr-3">Risk Score</th>
                <th className="py-2 pr-3">Risk Level</th>
              </tr>
            </thead>
            <tbody>
              {evidence.map((e) => (
                <tr key={e.evidenceId} className="border-b border-slate-800/50">
                  <td className="py-2 pr-3 font-mono text-cyan-400">{e.evidenceId}</td>
                  <td className="py-2 pr-3 text-slate-200">{e.filename}</td>
                  <td className="py-2 pr-3 text-slate-400">{e.type}</td>
                  <td className="py-2 pr-3 text-slate-300">{e.riskScore}/100</td>
                  <td className="py-2 pr-3"><RiskBadge level={e.riskLevel} /></td>
                </tr>
              ))}
            </tbody>
          </table>
        </section>

        {/* 4. Evidence Integrity */}
        <section className="mb-6 print-section">
          <h2 className={sectionTitle}>4. Evidence Integrity</h2>
          <div className="space-y-2">
            {evidence.map((e) => (
              <div key={e.evidenceId} className="flex items-center gap-3 text-xs">
                <span className="font-mono text-cyan-400 w-24">{e.evidenceId}</span>
                <span className="text-slate-200 w-32 truncate">{e.filename}</span>
                <IntegrityBadge status={e.integrity} />
                <span className="font-mono text-slate-500 truncate flex-1">{e.sha256.slice(0, 32)}...</span>
              </div>
            ))}
          </div>
        </section>

        {/* 5. Risk Distribution */}
        <section className="mb-6 print-section">
          <h2 className={sectionTitle}>5. Risk Distribution</h2>
          <div className="grid grid-cols-3 gap-4">
            <div className="rounded-lg border border-emerald-500/30 bg-emerald-500/5 p-3 text-center">
              <p className="text-2xl font-semibold text-emerald-400">{riskDistribution.low}</p>
              <p className="text-xs text-slate-400">Low Risk</p>
            </div>
            <div className="rounded-lg border border-amber-500/30 bg-amber-500/5 p-3 text-center">
              <p className="text-2xl font-semibold text-amber-400">{riskDistribution.medium}</p>
              <p className="text-xs text-slate-400">Medium Risk</p>
            </div>
            <div className="rounded-lg border border-red-500/30 bg-red-500/5 p-3 text-center">
              <p className="text-2xl font-semibold text-red-400">{riskDistribution.high}</p>
              <p className="text-xs text-slate-400">High Risk</p>
            </div>
          </div>
        </section>

        {/* 6. High-Risk Evidence */}
        <section className="mb-6 print-section">
          <h2 className={sectionTitle}>6. High-Risk Evidence</h2>
          {evidence.filter((e) => e.riskLevel === 'HIGH').length === 0 ? (
            <p className="text-sm text-slate-400">No high-risk evidence identified.</p>
          ) : (
            <div className="space-y-2">
              {evidence.filter((e) => e.riskLevel === 'HIGH').map((e) => (
                <div key={e.evidenceId} className="rounded-lg border border-red-500/20 bg-red-500/5 p-3">
                  <div className="flex items-center justify-between">
                    <span className="text-sm text-slate-200">{e.filename}</span>
                    <RiskBadge level="HIGH" />
                  </div>
                  <p className="text-xs text-slate-400 mt-1">Score: {e.riskScore}/100 · {e.evidenceId}</p>
                  {e.riskIndicators.length > 0 && (
                    <p className="text-xs text-slate-500 mt-1">Indicators: {e.riskIndicators.map((i) => i.label).join(', ')}</p>
                  )}
                </div>
              ))}
            </div>
          )}
        </section>

        {/* 7. Investigation Timeline */}
        <section className="mb-6 print-section">
          <h2 className={sectionTitle}>7. Investigation Timeline</h2>
          <div className="space-y-2">
            {timeline.map((t) => (
              <div key={t.id} className="flex items-start gap-3 text-xs">
                <span className="font-mono text-slate-500 w-28 shrink-0">{formatDateTime(t.timestamp)}</span>
                <span className="text-slate-200 flex-1">{t.description}</span>
                <RiskBadge level={t.risk} />
              </div>
            ))}
          </div>
        </section>

        {/* 8. AI-Assisted Analysis */}
        <section className="mb-6 print-section">
          <h2 className={sectionTitle}>8. AI-Assisted Analysis</h2>
          <p className="text-xs text-cyan-300 mb-3">AI-assisted prototype analysis — not a substitute for manual forensic review.</p>
          <div className="space-y-3">
            {evidence.filter((e) => e.aiSummary).slice(0, 5).map((e) => (
              <div key={e.evidenceId} className="rounded-lg border border-slate-800 p-3">
                <p className="text-sm text-slate-200">{e.filename}</p>
                <p className="text-xs text-slate-400 mt-1">{e.aiSummary}</p>
                <p className="text-xs text-slate-500 mt-1">Recommendation: {e.aiRecommendation}</p>
              </div>
            ))}
          </div>
        </section>

        {/* 9. Investigator Notes */}
        <section className="mb-6 print-section">
          <h2 className={sectionTitle}>9. Investigator Notes</h2>
          {notes.length === 0 ? (
            <p className="text-sm text-slate-400">No investigator notes recorded.</p>
          ) : (
            <div className="space-y-2">
              {notes.map((n, i) => (
                <div key={i} className="rounded-lg border border-slate-800 p-3">
                  <p className="text-sm text-slate-200">{n.content}</p>
                  <p className="text-xs text-slate-500 mt-1">{n.author} · {formatDateTime(n.timestamp)}</p>
                </div>
              ))}
            </div>
          )}
        </section>

        {/* 10. Audit Summary */}
        <section className="mb-6 print-section">
          <h2 className={sectionTitle}>10. Audit Summary</h2>
          <table className="w-full text-xs">
            <thead>
              <tr className="border-b border-slate-800 text-left text-slate-500">
                <th className="py-2 pr-3">Timestamp</th>
                <th className="py-2 pr-3">User</th>
                <th className="py-2 pr-3">Action</th>
                <th className="py-2 pr-3">Resource</th>
              </tr>
            </thead>
            <tbody>
              {auditLogs.slice(0, 10).map((log) => (
                <tr key={log.id} className="border-b border-slate-800/50">
                  <td className="py-2 pr-3 text-slate-400">{formatDateTime(log.timestamp)}</td>
                  <td className="py-2 pr-3 text-slate-300 truncate max-w-[140px]">{log.user}</td>
                  <td className="py-2 pr-3 text-slate-200">{log.action}</td>
                  <td className="py-2 pr-3 text-slate-400 font-mono truncate max-w-[140px]">{log.resource}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </section>

        {/* 11. Conclusion */}
        <section className="mb-6 print-section">
          <h2 className={sectionTitle}>11. Conclusion</h2>
          <p className="text-sm text-slate-300">{report.conclusion}</p>
          <div className="mt-4 rounded-lg border border-slate-800 p-3">
            <p className="text-xs text-slate-500">
              This report was generated by CYBERTRACE AI, a prototype digital forensics and cyber triage platform.
              All analysis is automated and intended to assist — not replace — manual forensic investigation.
              This document does not constitute legal admissibility of evidence.
            </p>
          </div>
        </section>

        {/* Footer */}
        <div className="border-t border-slate-800 pt-4 text-center text-xs text-slate-500">
          <p>Generated on {formatDateTime(report.generatedAt)} by {report.generatedBy}</p>
          <p className="mt-1">CYBERTRACE AI — Digital Forensics &amp; Cyber Triage Platform</p>
        </div>
      </Card>
    </div>
  );
}
